apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: NodePort
  ports:
  - port: 3306
  selector:
    app: mysql
  ports:
    - port: 3308
      targetPort: 3306
      nodePort: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: host-pods-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: host-pods-volume
        persistentVolumeClaim:
          claimName: task-pv-claim